version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: pgserver
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./dblocal:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  
  crawler:
    build: .
    command: uvicorn crawler_api.main:crawler_api --host 0.0.0.0
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgres